#SettingSort
sort:
  sortof:
    - series
---
#SpringSetting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dementyDD
    url: jdbc:mysql://localhost:3306/dementytest
    password: Technodvij1990
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
        id:
          new_generator_mappings: 'false'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

